


```{r}
# Import the dataset
# Loading the Dataset  into R
library(MASS)
data("Boston")
head(Boston)
```

```{r}
# Splitting of the dataset 
set.seed(2)
library(caTools)
#spluting the data set into 30-70
split <- sample.split(Boston$medv, SplitRatio = 0.7)
train <- subset(Boston, split == "TRUE")
test <- subset(Boston, split == "FALSE")
```

```{r}
library(lattice)
splom(~Boston[c(1:6,14)],groups=NULL,data=Boston,axis.line.tck=0,axis.text.alpha=0)
splom(~Boston[c(7:14)],groups=NULL, data=Boston,axis.line.tck=0,axis.text.alpha=0)
```
```{r}
# Studying the Rm and the Mdev correlation
plot(Boston$rm,Boston$medv, xlab="No of Rooms", ylab="Price")
abline(lm(Boston$medv~Boston$rm), col="red")
```

```{r}
model <- lm(medv~., data = train)
summary(model)
```

```{r}
# Now Using the Model to predict the output of the test set
predic <- predict(model , test)
predic
```

```{r}
# Comparing predictions with actual values 
plot(test$medv, type = "l" , lty = 1.8 , col="red")
lines(predic, type="l", col = "blue")
```
```{r}

library(modelr)
R2 = rsquare(model, data = Boston)
RMSE = rmse(model, data = Boston)
MAE = mae(model, data = Boston)
```

```{r}
cat("R2 Score - ", R2)
cat("\nRMSE Score - ", RMSE)
cat("\nMAE Score - ", MAE)
```


